[package]
name = "zarr_mex"
version = "0.0.1"
authors = ["Norman Rzepka <norman.rzepka@scalableminds.com>", "Alessandro Motta <alessandro.motta@brain.mpg.de>"]
build = "build.rs"

[dependencies]
zarrs = "0.23"
libc = "0.2"
serde_json = "1.0"
zarrs_http = "0.3.1"
rayon = "1"

[profile.release]
lto = true

[lib]
name = "zarr_mex"
crate-type = ["cdylib"]
