function zarrTest()
    path = '/Users/norman/scalableminds/webknossos/binaryData/Organization_X/l4_sample/segmentation/1';

    % Test read command
    bbox = [1, 2; 3074, 3075; 3074, 3075; 514, 515];
    data = zarrMex('read', path, bbox);
    assert(data == 988274);

    % Test write command
    data = cast(reshape(linspace(0, 999, 1000), [1, 10, 10, 10]), "uint32");
    bbox = [1, 2; 1, 11; 1, 11; 1, 11];
    zarrMex('write', path, bbox, data);
    data_Read = zarrMex('read', path, bbox);
    assert(isequal(data, data_Read));

    % Test create command
    test_path = '/tmp/zarr_test';
    if isfolder(test_path)
        rmdir(test_path, 's');
    end
    json = jsonencode(struct( ...
        'zarr_format', 3, ...
        'node_type', 'array', ...
        'shape', [100, 100, 100], ...
        'data_type', 'uint8', ...
        'chunk_grid', struct( ...
            'name', 'regular', ...
            'configuration', struct('chunk_shape', [32, 32, 32]) ...
        ), ...
        'chunk_key_encoding', struct( ...
            'name', 'default', ...
            'configuration', struct('separator', '/') ...
        ), ...
        'fill_value', 0, ...
        'codecs', {{ struct( ...
            'name', 'sharding_indexed', ...
            'configuration', struct( ...
                'chunk_shape', [32, 32, 32], ...
                'codecs', {{ struct('name', 'bytes') }}, ...
                'index_location', 'end', ...
                'index_codecs', {{ struct('name', 'bytes'), struct('name', 'crc32c') }} ...
            )) }} ...
    ));
    zarrMex('create', test_path, json);
    assert(isfile(fullfile(test_path, 'zarr.json')));

    % Compare zarr.json contents with original JSON
    zarr_json_path = fullfile(test_path, 'zarr.json');
    written_json = fileread(zarr_json_path);
    original_struct = jsondecode(json);
    written_struct = jsondecode(written_json);
    assert(isequal(original_struct, written_struct), ...
        'zarr.json contents do not match the original JSON');

    % Test resize command
    new_shape = [200, 150, 100];
    zarrMex('resize', test_path, new_shape);
    resized_json = fileread(zarr_json_path);
    resized_struct = jsondecode(resized_json);
    assert(isequal(resized_struct.shape, new_shape'), ...
        'Shape after resize does not match expected shape');

    % Test info command
    info = zarrMex('info', test_path);
    disp(info); 
    expected_bbox = [1, 201; 1, 151; 1, 101];
    assert(isequal(info.boundingBox, expected_bbox), ...
        'Bounding box does not match expected value');
    assert(strcmp(info.dataType, 'uint8'), ...
        'Data type does not match expected value');
    assert(isequal(info.chunkShape, [32, 32, 32]), ...
        'Chunk shape does not match expected value');
    assert(isequal(info.shardShape, [32, 32, 32]), ...
        'Shard shape does not match expected value');

end