name: MATLAB Tests

# Controls when the action will run.
on: [push]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run zarrBuild
        uses: matlab-actions/run-command@v2
        with:
          command: cd zarr-matlab, zarrBuild

      - name: Run zarrTest
        uses: matlab-actions/run-command@v2
        with:
          command: cd zarr-matlab, runtests(["ZarrTest"])

      - uses: actions/upload-artifact@v4
        with:
          name: mex-${{ matrix.os }}
          path: zarr-matlab/zarrMex.mex*
